---
- name: paloalto set dns, setup http backup user
  hosts: all
  connection: local

  collections:
      - paloaltonetworks.panos

  vars:
    palo_provider:
      api_key: LUFRPT1vR0YzdEFFMUhhSG93VHdRNzNJdDlhV1dQcDg9SWJGbllUaFMzQTN4OWF6bHR2SFYwYjZ2TVBLbWdvRXZFWGFvamFNVFpNaFNRMVFlbGtCcUlZT1JrTXpsWmRqdA==
      ip_address: "{{ ansible_host }}"



  tasks:
   - name: Add CR234312 to the firewall
     panos_security_rule:
      provider: '{{ palo_provider }}'
      ip_address: '{{ ansible_host }}'
      rule_name: 'CR234312'
      description: 'CR234312'
      source_zone: ['Inside']
      destination_zone: ['test1']
      source_ip: ['testaddress1']
      source_user: ['any']
      destination_ip: ['Test-two']
      category: ['any']
      application: ['any']
      service: ['Prod1-Services']
      hip_profiles: ['any']
      action: 'allow'
      commit: 'False'
