---
- name: paloalto set dns, setup http backup user
  hosts: all
  connection: local

  collections:
      - paloaltonetworks.panos

  vars:
    palo_provider:
      api_key: LUFRPT1vR0YzdEFFMUhhSG93VHdRNzNJdDlhV1dQcDg9SWJGbllUaFMzQTN4OWF6bHR2SFYwYjZ2TVBLbWdvRXZFWGFvamFNVFpNaFNRMVFlbGtCcUlZT1JrTXpsWmRqdA==
      ip_address: "{{ ansible_host }}"

  tasks:
  - name: Create service object 'ftp-tcp-21'
    panos_service_object:                  
     provider: '{{ palo_provider }}'            
     name: 'ftp-tcp-21'                
     destination_port: '21'              
     description: 'FTP on tcp/21'          
  - name: Create service object 'svc-tcp-8206'
    panos_service_object:                  
     provider: '{{ palo_provider }}'            
     name: 'svc-tcp-8206'                
     destination_port: '8206'              
     description: 'svc on tcp/8206'
  
  - name: Commiting all above changes     
    panos_commit_firewall:                
           provider: '{{ palo_provider }}'
