---
- name: paloalto add policies
  hosts: all
  connection: local

  collections:
      - paloaltonetworks.panos

  

  vars:
    palo_provider:
      api_key: LUFRPT1vR0YzdEFFMUhhSG93VHdRNzNJdDlhV1dQcDg9SWJGbllUaFMzQTN4OWF6bHR2SFYwYjZ2TVBLbWdvRXZFWGFvamFNVFpNaFNRMVFlbGtCcUlZT1JrTXpsWmRqdA==
      ip_address: "{{ ansible_host }}"
  tasks:
  - name: Create syslog profile
    panos_syslog_profile:
     provider: '{{ palo_provider }}'
     ip_address: '{{ ansible_host }}'
     name: 'POLICY_SYSLOG'
