---
- name: IPSEC_TUNNEL
  hosts: all
#  gather_facts: false
#  connection: local
  collections:
    - paloaltonetworks.panos

  vars:
      palo_provider:
        username: "admin"
        password: "AD@2010el"
        api_key: LUFRPT02SUNLWTFhOFdKQ2JqNHo5YXVVRUZaV3F2R0k9SWJGbllUaFMzQTN4OWF6bHR2SFYwWUdNT2N2STY2b0MzSlhjMG05QTZOcy9SOGVUbFNJeVkyV3N0SlZHK0dweA==

 

  tasks:
   - name: Add IPSec tunnel to IKE gateway profile
     panos_ipsec_tunnel:
      provider: '{{ palo_provider }}'
      username: "admin"
      password: "AD@2010el"
      api_key: LUFRPT02SUNLWTFhOFdKQ2JqNHo5YXVVRUZaV3F2R0k9SWJGbllUaFMzQTN4OWF6bHR2SFYwWUdNT2N2STY2b0MzSlhjMG05QTZOcy9SOGVUbFNJeVkyV3N0SlZHK0dweA==
      ip_address: '{{ ip_address }}'
      state: 'present'
      name: 'IPSecTunnel-Ansible'
      tunnel_interface: 'tunnel.2'
      ike_gtw_name: 'IKEGW-Ansible'
      ipsec_profile: 'default'
      commit: 'False'
