---
- name: paloalto set dns, setup http backup user
  hosts: all
  connection: local

  collections:
      - paloaltonetworks.panos

  vars:
    palo_provider:
      api_key: LUFRPT1vR0YzdEFFMUhhSG93VHdRNzNJdDlhV1dQcDg9SWJGbllUaFMzQTN4OWF6bHR2SFYwYjZ2TVBLbWdvRXZFWGFvamFNVFpNaFNRMVFlbGtCcUlZT1JrTXpsWmRqdA==
      ip_address: "{{ ansible_host }}"

  tasks:
  - name: Create service object 'ftp-tcp-21'
    panos_service_object:                  
     provider: '{{ palo_provider }}'            
     name: 'ssh-tcp-22'                
     destination_port: '22'              
     description: 'SSH on tcp/22'          
  - name: Create service object 'svc-tcp-8206'
    panos_service_object:                  
     provider: '{{ palo_provider }}'            
     name: 'mysql-tcp-3306'                
     destination_port: '3306'              
     description: 'MySQL on tcp/3306'
  
  - name: Commiting all above changes     
    panos_commit_firewall:                
           provider: '{{ palo_provider }}'
